[package]
authors = ["Eric Trombly <etrombly@yahoo.com>"]
name = "photos-rs"
version = "0.1.0"

[dependencies]
cogset = "0.2.0"
futures = "0.1.16"
futures-cpupool = "0.1.6"
gdk = "0.6.0"
gdk-pixbuf = "0.2.0"
geo = "0.6.2"
gtk = "0.2.0"
gtk-sys = "0.4.0"
hyper = "0.11.2"
hyper-tls = "0.1.2"
relm = "0.10.1"
relm-attributes = "0.10.0"
relm-derive = "0.10.0"
reqwest = "0.7.3"
rexiv2 = "0.5.0"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"
walkdir = "1.0.7"

[dependencies.chrono]
features = ["serde"]
version = "0.4.0"

[dependencies.location_history]
git = "https://github.com/etrombly/location_history"

[profile.release]
lto = true
