[package]
authors = ["Eric Trombly <etrombly@yahoo.com>"]
name = "photos-rs"
version = "0.1.0"
[dependencies]
cogset = "0.2.0"
futures = "0.1.14"
futures-cpupool = "0.1.5"
gdk = "0.5.3"
gdk-pixbuf = "0.1.3"
geo = "0.4"
gtk = "0.1.3"
gtk-sys = "0.3.4"
hyper = "0.11.2"
hyper-tls = "0.1.2"
odds = "0.2.25"
reqwest = "0.7.2"
rexiv2 = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
walkdir = "1.0.7"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.location_history]
git = "https://github.com/etrombly/location_history"

[dependencies.relm]
branch = "feature/futures-glib"
git = "https://github.com/antoyo/relm"

[dependencies.relm-attributes]
branch = "feature/futures-glib"
git = "https://github.com/antoyo/relm"

[dependencies.relm-derive]
branch = "feature/futures-glib"
git = "https://github.com/antoyo/relm"
[profile.release]
lto = true
